name: 🦑 Achievements
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 19 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  #push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: Suvraneel/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Suvraneel
          template: classic
          base: ""
          config_timezone: Asia/Calcutta
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          repositories_forks: yes
