name: LeetCode
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 6 * * *"}]
  # Lines below let you run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: LeetCode
        uses: Suvraneel/metrics@latest
        with:
          filename: metrics.plugin.leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
