name: Auto-approve Bot PRs
on:
  # Schedule updates (each hour)
  # schedule: [{cron: "0 19 * * *"}]
  # Lines below let you run workflow manually and on each commit
  #workflow_dispatch:
  push: {branches: ["master", "main"]}

pull_request_rules:
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
      - check-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge
