name: 🫀 People Plugin
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 19 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  #push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.people.followers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_size: 64
          plugin_people_limit: 0
          plugin_people_types: followers
