name: Followers
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.people.repository.svg
  token: ${{ secrets.METRICS_TOKEN }}
  base: ""
  template: repository
  repo: metrics
  plugin_people: yes
  plugin_people_types: followers, contributors, stargazers, watchers, sponsors
