
name: ⏱️ PageSpeed plugin (detailed)
on:
  schedule:
    - cron: '*/30 * * * *'
  #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: Suvraneel/metrics@master
        with:
          filename: metrics.plugin.pagespeed.detailed.svg
          token: NOT_NEEDED
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: ${{ secrets.WEBSITE_URL }}
          output_action: pull-request
          delay: 120
