name: Website Analysis Metrics
on:
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: Suvraneel/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Suvraneel
          template: classic
          base: ""
          config_timezone: Asia/Calcutta
          plugin_pagespeed: yes
          plugin_pagespeed_url: .user.website
