name: Website Analysis Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 6 * * *"}]
  # Lines below let you run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Detailed report
        uses: Suvraneel/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.detailed.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.METRICS_TOKEN }}
          plugin_pagespeed_url: https://suvraneel.github.io
