name: ⏱️ PageSpeed plugin (detailed)
uses: Suvraneel/metrics@master
with:
 filename: metrics.plugin.pagespeed.detailed.svg
 token: NOT_NEEDED
 plugin_pagespeed: yes
 plugin_pagespeed_detailed: yes
 plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
 plugin_pagespeed_url: ${{ secrets.WEBSITE_URL }}
 output_action: pull-request
 delay: 120
